verifyConditions: []
branches:
- main
plugins:
- '@semantic-release/commit-analyzer'
- - '@semantic-release/release-notes-generator'
  - preset: conventionalcommits
- - '@semantic-release/changelog'
  - changelogFile: CHANGELOG.md
- - '@semantic-release/git'
  - assets:
    - CHANGELOG.md
    message: "chore(release): ${nextRelease.version}\n\n${nextRelease.notes}"
