name: Release

on:
  push:
    branches:
    - 'main'

jobs:
  semantic-release:
    name: Run semantic-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@071ef4c9640be3700de2aa7f39e8f4038e0269ed
      with:
        extra_plugins: |
          conventional-changelog-conventionalcommits@5.0.0
          @semantic-release/changelog@6.0.1
          @semantic-release/git@10.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
